const STORAGE={profile:'wd_profile_v1',reports:'wd_reports_v1',chat:'wd_chat_v1'};
const avatars=['🐶','🐕','🦮','🐕‍🦺','🐩','🐾','🦴','🎾'];
const reportTypes=[{id:'danger',icon:'❗',label:'Gevaar',marker:'danger'},{id:'vegetation',icon:'🌿❗',label:'Vegetatie',marker:'vegetation'},{id:'dirty',icon:'💩',label:'Vervuiling',marker:'danger'},{id:'road',icon:'🚧',label:'Pad / weg',marker:'danger'},{id:'fun',icon:'💚',label:'Leuke plek',marker:'fun'},{id:'walk',icon:'🐾',label:'Samen wandelen',marker:'social'},{id:'spotted',icon:'🐕',label:'Hond gespot',marker:'social'},{id:'lost',icon:'🚨',label:'Vermist / gevonden',marker:'lost'}];
const vegetationKinds=['Grasaren','Berenklauw','Eikenprocessierups','Brandnetels','Giftige plant','Stekelige struiken','Anders'];
let selectedAvatar=avatars[0],selectedReportType=null,selectedVegetation=null,activeFilter='all';
let map,reportLayer,offleashLayer,onleashLayer;
const seedReports=[{id:'seed1',type:'vegetation',subtype:'Grasaren',text:'Veel grasaren langs de rand van het pad.',lat:52.19,lng:5.39,time:'Vandaag 10:20',author:'Pip',confirmed:6},{id:'seed2',type:'danger',text:'Kleine glasscherven naast het wandelpad.',lat:52.11,lng:5.22,time:'Vandaag 09:45',author:'Bowie',confirmed:3},{id:'seed3',type:'fun',text:'Fijne schaduwplek met water in de buurt.',lat:52.15,lng:5.31,time:'Gisteren',author:'Luna',confirmed:9}];
const el=id=>document.getElementById(id);
function loadJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function saveJSON(key,value){localStorage.setItem(key,JSON.stringify(value))}
function toast(message){const t=el('toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),2400)}
function profile(){return loadJSON(STORAGE.profile,null)}
function setupNavigation(){document.querySelectorAll('[data-view]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));el('profileQuick').addEventListener('click',()=>showView('profile'))}
function showView(view){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));el(`view-${view}`).classList.add('active');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===view));if(view==='map'&&map)setTimeout(()=>map.invalidateSize(),40)}
function setupProfile(){const grid=el('avatarGrid');grid.innerHTML=avatars.map((a,i)=>`<button type="button" class="avatar-choice ${i===0?'selected':''}" data-avatar="${a}">${a}</button>`).join('');grid.addEventListener('click',e=>{const b=e.target.closest('[data-avatar]');if(!b)return;selectedAvatar=b.dataset.avatar;document.querySelectorAll('.avatar-choice').forEach(x=>x.classList.toggle('selected',x===b))});el('editProfile').addEventListener('click',()=>openProfileDialog());el('onboardingForm').addEventListener('submit',e=>{e.preventDefault();const name=el('onboardingName').value.trim();if(!name){toast('Vul eerst een naam in 🐾');return}saveJSON(STORAGE.profile,{name,avatar:selectedAvatar,createdAt:new Date().toISOString()});updateProfileUI();el('onboardingDialog').close();toast(`Welkom, ${name}! 🐾`)});updateProfileUI();if(!profile())setTimeout(()=>openProfileDialog(true),280)}
function openProfileDialog(first=false){const p=profile();if(p){el('onboardingName').value=p.name;selectedAvatar=p.avatar}else if(first){el('onboardingName').value='';selectedAvatar=avatars[0]}document.querySelectorAll('.avatar-choice').forEach(x=>x.classList.toggle('selected',x.dataset.avatar===selectedAvatar));el('onboardingDialog').showModal()}
function updateProfileUI(){const p=profile(),avatar=p?.avatar||'🐶',name=p?.name||'Jouw hond';el('profileQuickAvatar').textContent=avatar;el('navProfileAvatar').textContent=avatar;el('profileAvatarBig').textContent=avatar;el('profileName').textContent=name;el('profileSubtitle').textContent=p?'Klaar om te snuffelen':'Maak je hondenprofiel af';el('myReportCount').textContent=loadJSON(STORAGE.reports,[]).length}
function initMap(){if(typeof L==='undefined'){document.querySelector('.map').innerHTML='<div style="padding:120px 24px;text-align:center">De kaart kon niet laden. Controleer je internetverbinding.</div>';return}map=L.map('map',{zoomControl:false}).setView([52.14,5.29],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);L.control.zoom({position:'bottomright'}).addTo(map);reportLayer=L.layerGroup().addTo(map);offleashLayer=L.layerGroup().addTo(map);onleashLayer=L.layerGroup().addTo(map);drawDogAreas();drawReports();el('locateBtn').addEventListener('click',locateUser);setupFilters();setupLayerToggles()}
function drawDogAreas(){const demoOff=[[[52.165,5.275],[52.168,5.287],[52.161,5.293],[52.156,5.281]]],demoOn=[[[52.105,5.340],[52.111,5.352],[52.102,5.363],[52.096,5.348]]];demoOff.forEach(coords=>L.polygon(coords,{color:'#5c9349',weight:3,fillColor:'#7db46d',fillOpacity:.28}).bindPopup('<b>🐕 Demo losloopgebied</b><br>Loslopen toegestaan · kaartvlak').addTo(offleashLayer));demoOn.forEach(coords=>L.polygon(coords,{color:'#c88d22',weight:3,dashArray:'6 6',fillColor:'#f2be4d',fillOpacity:.20}).bindPopup('<b>🦮 Demo aanlijngebied</b><br>Hond aan de lijn · kaartvlak').addTo(onleashLayer))}
function allReports(){return[...seedReports,...loadJSON(STORAGE.reports,[])]}
function drawReports(){if(!reportLayer)return;reportLayer.clearLayers();allReports().filter(matchesFilter).forEach(r=>{const type=reportTypes.find(t=>t.id===r.type)||reportTypes[0],icon=L.divIcon({className:'',html:`<div class="marker-badge marker-${type.marker}">${type.icon}</div>`,iconSize:[38,38],iconAnchor:[19,19]});const marker=L.marker([r.lat,r.lng],{icon}).addTo(reportLayer);marker.on('click',()=>openReportDetail(r))})}
function matchesFilter(r){if(activeFilter==='all')return true;if(activeFilter==='offleash')return false;if(activeFilter==='fun')return['fun','walk','spotted'].includes(r.type);return r.type===activeFilter}
function setupFilters(){el('filterRow').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;activeFilter=b.dataset.filter;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));drawReports();if(activeFilter==='offleash'){if(!map.hasLayer(offleashLayer))offleashLayer.addTo(map);toast('Losloopgebieden staan als groene vlakken op de kaart')}})}
function setupLayerToggles(){document.querySelectorAll('[data-layer]').forEach(cb=>cb.addEventListener('change',()=>{const layer={offleash:offleashLayer,onleash:onleashLayer,reports:reportLayer}[cb.dataset.layer];if(cb.checked)layer.addTo(map);else map.removeLayer(layer)}));el('legendToggle').addEventListener('click',()=>el('legendBody').classList.toggle('closed'))}
function locateUser(){if(!navigator.geolocation){toast('Locatie wordt niet ondersteund op dit toestel');return}toast('Even snuffelen naar je locatie…');navigator.geolocation.getCurrentPosition(pos=>{const{latitude,longitude}=pos.coords;map.setView([latitude,longitude],15);L.circleMarker([latitude,longitude],{radius:8,color:'#3a76a8',fillColor:'#6fb4e8',fillOpacity:1,weight:3}).addTo(map).bindPopup('Jij bent hier — deze locatie wordt niet openbaar gedeeld.').openPopup()},()=>toast('Locatie niet gedeeld. Geen probleem — de kaart blijft werken.'),{enableHighAccuracy:false,timeout:8000,maximumAge:60000})}
function setupReports(){el('reportFab').addEventListener('click',()=>{resetReportForm();el('reportDialog').showModal()});el('reportTypes').innerHTML=reportTypes.map(t=>`<button type="button" class="report-type" data-report-type="${t.id}"><span>${t.icon}</span>${t.label}</button>`).join('');el('vegetationKinds').innerHTML=vegetationKinds.map(v=>`<button type="button" class="subtype" data-subtype="${v}">${v}</button>`).join('');el('reportTypes').addEventListener('click',e=>{const b=e.target.closest('[data-report-type]');if(!b)return;selectedReportType=b.dataset.reportType;selectedVegetation=null;document.querySelectorAll('.report-type').forEach(x=>x.classList.toggle('selected',x===b));el('reportDetails').classList.remove('hidden');el('vegetationKinds').classList.toggle('hidden',selectedReportType!=='vegetation')});el('vegetationKinds').addEventListener('click',e=>{const b=e.target.closest('[data-subtype]');if(!b)return;selectedVegetation=b.dataset.subtype;document.querySelectorAll('.subtype').forEach(x=>x.classList.toggle('selected',x===b))});el('reportForm').addEventListener('submit',e=>{e.preventDefault();if(!selectedReportType){toast('Kies eerst wat je hebt gespot');return}if(selectedReportType==='vegetation'&&!selectedVegetation){toast('Welke vegetatie heb je gezien?');return}const center=map.getCenter(),p=profile(),text=el('reportText').value.trim()||defaultReportText(selectedReportType,selectedVegetation),reports=loadJSON(STORAGE.reports,[]);reports.push({id:crypto.randomUUID?.()||String(Date.now()),type:selectedReportType,subtype:selectedVegetation,text,lat:center.lat,lng:center.lng,time:'Zojuist',author:p?.name||'Anonieme hond',confirmed:0});saveJSON(STORAGE.reports,reports);drawReports();updateProfileUI();el('reportDialog').close();toast('🐾 Dankjewel! Je melding staat op deze demo-kaart.')})}
function resetReportForm(){selectedReportType=null;selectedVegetation=null;el('reportText').value='';el('reportDetails').classList.add('hidden');el('vegetationKinds').classList.add('hidden');document.querySelectorAll('.report-type,.subtype').forEach(x=>x.classList.remove('selected'));el('reportLocationText').textContent='Plaats op het midden van de kaart'}
function defaultReportText(type,sub){const t=reportTypes.find(x=>x.id===type);return sub?`${sub} gespot — voorzichtig met je hond.`:`${t?.label||'Melding'} gespot.`}
function openReportDetail(r){const t=reportTypes.find(x=>x.id===r.type)||reportTypes[0];el('detailContent').innerHTML=`<div class="detail-icon">${t.icon}</div><h2>${escapeHTML(r.subtype||t.label)}</h2><div class="detail-meta">${escapeHTML(r.time)} · gemeld door ${escapeHTML(r.author||'hondenbezitter')}</div><p class="detail-body">${escapeHTML(r.text)}</p><div class="notice-card">🐾 ${Number(r.confirmed||0)} hondenbezitters bevestigen dit</div><div class="detail-actions"><button type="button" class="primary" id="confirmReport">👍 Nog steeds</button><button type="button" class="primary" id="thankReport">💚 Bedankt</button></div>`;el('detailDialog').showModal();el('confirmReport').onclick=()=>{toast('Bevestiging geregistreerd in deze demo');el('detailDialog').close()};el('thankReport').onclick=()=>{toast('💚 Bedankje gegeven');el('detailDialog').close()}}
function escapeHTML(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setupChat(){let messages=loadJSON(STORAGE.chat,[{id:'welcome',name:'Whatsup dog',text:'Welkom in de buurtchat! 🐾',mine:false}]);const render=()=>{el('chatList').innerHTML=messages.map(m=>`<div class="bubble ${m.mine?'mine':''}"><small>${escapeHTML(m.name)}</small>${escapeHTML(m.text)}</div>`).join('')};el('chatForm').addEventListener('submit',e=>{e.preventDefault();const input=el('chatInput'),text=input.value.trim();if(!text)return;const p=profile();messages.push({id:String(Date.now()),name:p?.name||'Jij',text,mine:true});saveJSON(STORAGE.chat,messages);input.value='';render();setTimeout(()=>el('chatList').lastElementChild?.scrollIntoView({behavior:'smooth'}),20)});render()}
function setupAlerts(){el('pushDemo').addEventListener('click',async()=>{if(!('Notification'in window)){toast('Deze browser ondersteunt geen webmeldingen');return}if(Notification.permission==='default')await Notification.requestPermission();if(Notification.permission==='granted'){new Notification('🌿❗ Whatsup dog',{body:'Grasaren gemeld in je wandelgebied.'});toast('Testmelding verstuurd')}else toast('Meldingen zijn niet toegestaan — je kunt ze later aanzetten.')})}
function registerServiceWorker(){if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{})}
setupNavigation();setupProfile();setupReports();setupChat();setupAlerts();initMap();registerServiceWorker();
